### ISSUE TITLE
Resolution Scale do not work on Amd 6000 cards

### ISSUE THREAD

**Issue by vijit92** [xenia-project/xenia#1774] opened 2021-04-08 10:41 UTC
Rov/d3d12 resolution scale is supported on cards above Vega (as per another thread) but in rdna2 cards (rx 6800/6900 xt) it cant be used.

When rov is enabled game do not run and black screen appears.

**Comment by RareMv** [comment] 2022-01-11 23:00
ROV doesn't really work on AMD overall I'd say. It's been completely non functional on any Xenia build on any driver on RDNA1 (I have a 5700 XT) and ROV is supposed to be supported, but no dice.

**Comment by Margen67** [comment] 2022-01-14 13:42
Resolution scaling doesn't require ROV anymore.

From Discord:
```
[2:20 AM] TriΔng3l: That crash with ROV still happens, I'm going to make a workaround for a part of the cases soon though
[2:21 AM] TriΔng3l: well, not really a workaround, just a slightly different approach of doing the same thing
[2:29 AM] TriΔng3l: manual ddx/ddy of SV_Position.z instead of EvaluateAttributeAtSample, should be better for some other reasons (easier depth biasing, fixed-function viewport handling)
```

**Comment by Margen67** [comment] 2022-05-29 07:47
Duplicate of #1251

**Closed by Margen67** 2022-05-29 07:47 UTC
Labels: bug, gpu-d3d12
