### ISSUE TITLE
Wired graphics on Forza Horizon 1

### ISSUE THREAD

**Issue by PIndividual** [xenia-project/xenia#1915] opened 2021-11-28 03:01 UTC
[//]: # The terrain won't load and plants are just floating in Forza Horizon 1

[//]: # (Describe what should happen:)At least there should be other terrains
![image](https://user-images.githubusercontent.com/62368342/143727300-b77754ee-bf26-4e17-94c4-ef291bf098e2.png)
[//]: # (If applicable, provide a callstack here - esp. for crashes)

[//]: # (If applicable, upload a logfile and link it here
[xenia.log](https://github.com/xenia-project/xenia/files/7612728/xenia.log)
)

**Comment by illusion0001** [comment] 2021-11-28 04:06
Duplicate of #1533

**Closed by illusion0001** 2021-11-28 04:06 UTC
