### ISSUE TITLE
 Intel HD GT1 - Xenia only crash with all settings with Intel SDE

### ISSUE THREAD

**Issue by AD010** [xenia-project/xenia#1763] opened 2021-02-26 11:32 UTC
please add support Intel HD GT1 and CPU without AVX to Xenia. Master and Canary only crash on games logo with all settings with Intel SDE (emulator CPU Instructions), latest versions crash in compiling shaders

**Comment by Triang3l** [comment] 2021-02-26 11:39
The AVX part is duplicate of #603, and it won't be fixed any time soon — requires changes in around 600 places in the code, and hard to test (because if we miss some instruction, it will still work on developers' hardware).

For GT1, reproduction info is needed — the name of the game, steps to do in the game to locate a place using the shader that causes the crash. I do, however, remember some pipeline state objects failing to be created on Intel HD Graphics 4400 at least in Halo 3.

**Comment by AD010** [comment] 2021-02-26 12:01
The Incredible Hulk (2008) and Vigilante 8 Arcade, p.s. on RPCS3 all games (on all settings) have black or white screen without sounds, my Intel HD have full support OpenGL 1-4.3


[shareable.zip](https://github.com/xenia-project/xenia/files/6049487/shareable.zip)

**Comment by AD010** [comment] 2021-02-26 12:01
> 
> 
> The AVX part is duplicate of #603, and it won't be fixed any time soon — requires changes in around 600 places in the code, and hard to test (because if we miss some instruction, it will still work on developers' hardware).
> 
> For GT1, reproduction info is needed — the name of the game, steps to do in the game to locate a place using the shader that causes the crash (or the shader cache file for that game). I do, however, remember some pipeline state objects failing to be created on Intel HD Graphics 4400 at least in Halo 3.

The Incredible Hulk (2008) and Vigilante 8 Arcade, p.s. on RPCS3 all games (on all settings) have black or white screen without sounds, my Intel HD have full support OpenGL 1-4.3
[shareable.zip](https://github.com/xenia-project/xenia/files/6049491/shareable.zip)

**Closed** 2021-02-26 12:41 UTC
Labels: invalid
