### ISSUE TITLE
No Audio connected; crash of guest 

### ISSUE THREAD

**Issue by TiloGit** [xenia-project/xenia#1776] opened 2021-04-16 05:39 UTC
(Describe what's going wrong:)
Computer has no speaker/audio plugged in. guest crashes.  
log shows: 
` !> F8000028 IXAudio2::CreateMasteringVoice failed with -7FF8FB70`

see also https://github.com/xenia-project/game-compatibility/issues/1704#issuecomment-820917472

 (Describe what should happen:  Maybe bit more graceful handling this condition. 

(If applicable, provide a callstack here - esp. for crashes)  sorry don't 

 (If applicable, upload a logfile and link it here)
log has CRASH DUMP  [xenia.log](https://github.com/xenia-project/xenia/files/6322729/xenia.log)

**Comment by illusion0001** [comment] 2021-04-16 06:10
Duplicate of #1319

**Closed by illusion0001** 2021-04-16 06:10 UTC

**Comment by TiloGit** [comment] 2021-04-17 03:37
Thanks for the quick update. 
Was wondering if that could/should be handled more gracefully but looks like no interest for that. Anyhow cheers.

**Comment by Margen67** [comment] 2022-02-03 08:05
#1967
