### ISSUE TITLE
Feature Request: Skip AVX Checks for Cpus that are beefy but too old to have AVX 

### ISSUE THREAD

**Issue by washingleavesandthensome23-434** [xenia-project/xenia#1658] opened 2020-10-05 14:44 UTC
[//]: # (Describe what's going wrong:)

[//]: # (Describe what should happen:)
well simple, remove AVX requirement make it supported but not a must since theres a ton of old beefy cpus out there like the 5690 that still hold some grunt for emulation , thanks
[//]: # (If applicable, provide a callstack here - esp. for crashes)
none
[//]: # (If applicable, upload a logfile and link it here)
none

**Comment by Margen67** [comment] 2020-10-05 14:47
Duplicate of #1501 #603

**Comment by washingleavesandthensome23-434** [comment] 2020-10-05 14:49
interesting....

**Comment by illusion0001** [comment] 2020-10-05 14:53
Ugh

**Closed by illusion0001** 2020-10-05 14:53 UTC
Labels: invalid

**Comment by Triang3l** [comment] 2020-10-05 15:08
You can create a pull request with AVX instructions (can be located by searching for `e.v` in `cpu/backend/x64`) replaced with their SSE equivalents, and with two-operand form support (we have things like EmitCommutative* for scalar instructions already, a similar concept could work here too), in 620 places, if it works correctly and passes all the same tests as the current AVX implementation passes, we'll possibly merge it.

**Comment by washingleavesandthensome23-434** [comment] 2020-10-05 15:10
ok that could be a solution here , hope someone takes this on would be neat for sure
