### ISSUE TITLE
Save System 'Not enough space' (solved)

### ISSUE THREAD

**Issue by Parovozik** [xenia-project/xenia#784] opened 2017-08-20 18:39 UTC
I tried many games and sometimes saw message 'Not enough free space...'.
Example: Brave, Bully, Phineas and Ferb Quest for Cool Stuff, Red Dead Redemption, Spongebob Plankton Robotic Revenge, Wipeout Create and Crush and other.
This specific error and I solved it as follows:
**Path to file [...xenia-master\src\xenia\kernel\xam\xam_content.cc]**

> 28      static const DeviceInfo dummy_device_info_ = {
> 29      0xF00D0000,
> 30      1,
> 31      60ull * 1024ull * 1024ull * 1024ull,  // 60GB
> 32      27ull * 1024ull * 1024ull * 1024ull,  // 27GB, so it looks a little used.
> 33      L"Dummy HDD",
> 34      };

In original there 120GB/100GB
I think this is absolutely safe and should be added to the master build :)

# Screenshots from xenia-master without it fix
![bandicam 2017-08-20 18-51-30-858](https://user-images.githubusercontent.com/19775644/29497378-6113c9d6-85ef-11e7-87ae-8340634027a1.jpg)
![bandicam 2017-08-20 18-40-55-052](https://user-images.githubusercontent.com/19775644/29497387-7783c432-85ef-11e7-86de-6d1a9a6d8491.jpg)
![bandicam 2017-08-20 18-40-05-973](https://user-images.githubusercontent.com/19775644/29497388-7ab3a550-85ef-11e7-9b35-27b30bbaaa9b.jpg)
![bandicam 2017-08-20 18-39-14-984](https://user-images.githubusercontent.com/19775644/29497390-8099d58e-85ef-11e7-9e8e-7f0a0a7652fd.jpg)
![bandicam 2017-08-20 18-38-07-627](https://user-images.githubusercontent.com/19775644/29497391-83302bea-85ef-11e7-828a-075dd3c2fe5a.jpg)

**Comment by SonofUgly** [comment] 2017-08-21 00:43
Also fixes saving in Red Dead Redemption https://github.com/xenia-project/game-compatibility/issues/108

**Comment by Parovozik** [comment] 2017-08-21 01:04
@SonofUgly Yes, i tried, this works for Red Dead Redemption too :)

**Comment by Parovozik** [comment] 2018-01-24 18:12
@DrChat, can you add this fix to 'master' from 1st message? (just i dont know how it make :D )

**Comment by DrChat** [comment] 2018-01-24 18:15
Why does decreasing the available space fix these games?

There's the chance that applying this fix will break other games, so we should try to understand why this is happening in the first place.

**Comment by Parovozik** [comment] 2018-01-25 15:20
I think there overload for some variable and return as 'zero' or something else. I tried many games, this not effect for games when save-states is works before, only fixed 'not enough space' error

**Comment by Parovozik** [comment] 2018-03-04 10:58
I tried different values:
Default 120/100 - Not enough free space on hdd error
120/99 - OK
120/101 - OK
60/23 - OK
500/222 - OK

**Comment by goedzo** [comment] 2018-11-17 15:53
Why is there no PR created from this solution? I run into the same issue with quite a lot of games.

**Comment by goedzo** [comment] 2018-11-17 16:02
Well, then I just create the PR myself to get this one fixed :)

**Comment by goedzo** [comment] 2018-11-17 20:20
Ps. Here is the cause: Sorry but it's not a blind guess actually. It's caused by an overflow and incorrect HD detection in these games. When trying to detect the free space of the storage based on the hd inside the 360. There are various hd sizes in the original 360 and not all the games detect the disk size properly. In some cases the game thinks there is a 60gb disk inside that is 100gb full. That causes it to think it's full. In other cases the game just writes without checking and checks for an exception. This pr makes sure to set the hd size to 60gb to match the size inside the emulated xbox device.

Hope this explains the cause this issue for you.

**Comment by Parovozik** [comment] 2018-11-18 20:02
This error occurs for all these games in the same way. And this is not a 60GB problem, because the error disappears, for example, at 120 \ 101 or 120 \ 99 (but it is trouble at 120 \ 100)

**Comment by ruthan** [comment] 2019-09-20 00:10
I have still problem with Gear of War 3

**Comment by Margen67** [comment] 2019-10-28 06:31
Duplicate of #653.

**Closed by Margen67** 2019-10-28 06:31 UTC
Labels: bug
