### ISSUE TITLE
Issue with last D3D12 change "Compact float constants and don't split them into pages"

### ISSUE THREAD

**Issue by LuismaSP89** [xenia-project/xenia#1219] opened 2018-09-30 20:39 UTC
Issue in Eternal sonata (Don´t know if happens in other games but surely yes) 

Build c4599ff2/sep 30 (Compact float constants and don't split them into pages):

![after](https://user-images.githubusercontent.com/12205048/46262430-61b9b600-c501-11e8-923f-d6b24356f3cc.jpg)

Build eb50ebd8/Sep 29 (Write to 8_8_8_8_GAMMA in gamma space):

![before](https://user-images.githubusercontent.com/12205048/46262429-61b9b600-c501-11e8-99d3-fd502222b4ac.jpg)

**Comment by LuismaSP89** [comment] 2018-09-30 20:47
Log Build c4599ff (sep 30):
[Log Build c4599ff (sep 30).zip](https://github.com/xenia-project/xenia/files/2432043/Log.Build.c4599ff.sep.30.zip)

Log Build eb50ebd (Sep 29):
[Log Build eb50ebd (Sep 29).zip](https://github.com/xenia-project/xenia/files/2432044/Log.Build.eb50ebd.Sep.29.zip)

**Comment by Triang3l** [comment] 2018-09-30 21:34
Shader constants are heavily broken right now, and they probably always were, but now this just became more prominent. Seems that the issue is related to descriptor updating. Currently searching for a fix.

**Comment by Triang3l** [comment] 2018-10-01 17:17
Fixed in 2588aab89de6ddf60e0ced0aed4abea4e86c5fd1 — the shader translator was not adding constants to the list of used constants for single-operand scalar instructions.

**Closed by Triang3l** 2018-10-01 17:17 UTC
