### ISSUE TITLE
only Half Screen working in many Games

### ISSUE THREAD

**Issue by pillemats** [xenia-project/xenia#1078] opened 2018-01-16 07:43 UTC
hey there 

i have a graphic problem:

in many games like sonic the hedgehog and nfs most wanted i have only ob bottom a working screen in half size. the other size is black or white..

my hw:

i7 3770
16gb ddr3
nvidia gtx1050ti

need some help

**Comment by raynebc** [comment] 2018-01-16 08:10
Not sure if it's related, but one game I'd tested several weeks ago with OpenGL rendered to just one quarter of the Xenia program window.

**Comment by pillemats** [comment] 2018-01-16 09:02
How can i change from Vulkan to opengl?

**Comment by Razzile** [comment] 2018-01-16 16:56
launch xenia from the command line with the `--gpu=opengl` flag

**Comment by pillemats** [comment] 2018-01-16 16:59
What is command line ? How it works

**Comment by pillemats** [comment] 2018-01-16 17:24
C:\Users\HyperPIE>"H:\HyperPC\Emulators\_Experimental\Xenia Master\xenia.exe --gpu=opengl"
Der Befehl ""H:\HyperPC\Emulators\_Experimental\Xenia Master\xenia.exe --gpu=opengl"" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

**Comment by Baikal32** [comment] 2018-01-17 00:52
That's happening because the command line flag is inside the quotes. It shouldn't be part of the file path. You're also in the wrong directory.
Try typing this in cmd:
```
cd "H:\HyperPC\Emulators_Experimental\Xenia Master\"
xenia.exe --gpu=gl4
```

**Comment by DiamondMaster07** [comment] 2018-01-22 18:09
In NFS MW, half of the screen isn't visible(covered by a chunk of the last successfully rendered frame, usually a frame of a FMW or a frame from ingame), in ingame, that area works, but often freezes for a second or more

**Comment by akinwhite** [comment] 2018-02-04 19:15
@Baikal32 I'm having the same issue, I tried what you said but all that made the game's resolution about a quarter of the xenia window and makes it crash with the first in-game cutscene, any other suggestions?

**Comment by LuismaSP89** [comment] 2018-02-14 16:46
This happens to me in Eternal sonata, no matters if Opengl or Vulkan backend is used.

**Comment by Margen67** [comment] 2018-04-19 19:17
Lego Star Wars: The Complete Saga now only shows the HUD during gameplay:
![capture](https://user-images.githubusercontent.com/3462541/39010969-0eee2e0a-43c5-11e8-90d6-e30047195452.PNG)

Pocketbike Racer displays a completely black screen.

**Comment by LuismaSP89** [comment] 2018-04-19 22:07
Seems partially fixed for resident evil 6 (Intro screen shows diagonal half screen, other screens works ok) 
I can´t test it for eternal sonata. Since some months ago, it have blackscreen (sound and input works)

**Comment by Margen67** [comment] 2018-04-20 06:04
Eternal Sonata Demo partially renders the menu:
![etd1](https://user-images.githubusercontent.com/3462541/39032985-cdee83e0-4424-11e8-9f52-a6ab0f4ec43a.png)
I get this error after that screen:
![etd2](https://user-images.githubusercontent.com/3462541/39033174-a761ee46-4425-11e8-8b7a-829c8b28adcd.png)

**Comment by LuismaSP89** [comment] 2018-04-20 14:57
This is the only screen that shows for me (Full game, not demo) and yes, the "Graphics device lost" error, happens in some games for me too.

![screen 1](https://user-images.githubusercontent.com/12205048/39058249-8d30b08e-44bb-11e8-9551-4b335788cbc7.jpg)

Like I said, the game was working some months ago (only half screen, but working) I´ll try to bisect the last working build.

**Comment by DiamondMaster07** [comment] 2018-04-20 20:33
In NFSMW05, the 3D part of the main menu is completely covered by a black screen and only the HUD is visible. In free-roaming, the black screen is flashing on top of the 3D part(tested on https://github.com/benvanik/xenia/commit/2b66a1b68fca2be2a6827f69f9774f7b88287c5a but this has been an issue for a while now)
![desktop screenshot 2018 04 20 - 22 29 57 92](https://user-images.githubusercontent.com/26389402/39072297-6aba6458-44ea-11e8-987d-ca95c5907b84.png)
In NFS Undercover, 3D part is completely covered by black screen(this is a beta/dev build of the game, but the final game has the same issue)
![desktop screenshot 2018 04 20 - 22 31 25 96](https://user-images.githubusercontent.com/26389402/39072387-a5a94570-44ea-11e8-9231-a82416867bd8.png)

**Comment by LuismaSP89** [comment] 2018-04-20 21:12
The latest working build is from 2018/02/14 (After that, opengl crashes in all builds until today, so, I can´t test if Eternal sonata runs now properly) and Vulkan shows blackscreen with background sound for this game.

Changelog of the build from 2018/02/16 (Problems with opengl started with this):

* [Base] Faster copy-and-swap routines
* [Vulkan] Buffers typically aren't aligned.
* [Vulkan] Update the loader to SDK 1.0.68.0
* [JIT] Apply the same ZeroExtend/Truncate to rlwimix and rlwnmx
* [Core] Protect the last 64kb of memory
* [Base] Enable aligned copy and swap routines
* [JIT] New opcodes: OPCODE_LOAD_OFFSET and OPCODE_STORE_OFFSET
* [JIT] Comment the offsets in PPCContext
* [CPU] Check for RawModule memory allocation success
* [JIT] rlwinmx: Use Truncate/ZeroExtend instead of And 0xFFFFFFFF
* [Travis] Fix Travis

Image attached from latest working build (2018/02/14)
![screen 1](https://user-images.githubusercontent.com/12205048/39074053-3c79c470-44f0-11e8-94b6-bf30e7e57a47.jpg)

**Comment by Margen67** [comment] 2019-10-28 05:57
Duplicate of #586.

**Closed by Margen67** 2019-10-28 05:57 UTC
Labels: duplicate
