### ISSUE TITLE
Controller mapping!!!

### ISSUE THREAD

**Issue by Mechanical-sanity** [xenia-project/xenia#1378] opened 2019-06-14 00:23 UTC
Xenia needs a good controller mapper. I have a generic pc controller, but I can't use it to play xenia. so can someone add some good controller mapping?

**Comment by Ulquiorr4-Cifer** [comment] 2019-06-14 01:17
Use [x360ce](https://github.com/x360ce/x360ce) to make your controller appear as xbox360 controller, that way it will work with xenia

**Comment by Margen67** [comment] 2019-07-02 13:03
Duplicate of #1333

**Closed** 2019-07-04 02:48 UTC
Labels: duplicate
