### ISSUE TITLE
Xenia cannot run more than one game across a single instance

### ISSUE THREAD

**Issue by OfficerObese** [xenia-project/xenia#641] opened 2016-12-03 11:09 UTC
games crashing almost immediatly returns with error originating from line 856 in memeory.cc on 8gb ram 840m and intel core i5 4210u the last version of xenia i know works was built around the 25 of november before this issue started occuring

**Comment by PcDivision** [comment] 2016-12-03 11:10
i did some debugging trying to fix the issue but was unable to

**Comment by PcDivision** [comment] 2016-12-03 11:10
xenia works fine when using --gpu=null

**Comment by maxton** [comment] 2016-12-03 19:58
Can you find the commit at which things stopped working? And also try --gpu=gl4 and --gpu=vulkan

**Comment by DrChat** [comment] 2016-12-04 01:15
This probably never worked.
Would be something worth looking into, as this would deal with shutdown and initialization of Xenia.

At the moment I suspect we're not completely cleaning up Xenia after we leave a game, and it will just crash when loading a new game.

**Comment by PcDivision** [comment] 2016-12-04 12:37
ive done both gpu gl4 and gpu vulkan gl4 starts the game for about 2 seconds and then crashes

**Comment by PcDivision** [comment] 2016-12-04 12:37
it has somthing to do with memory allocation?

**Comment by PcDivision** [comment] 2016-12-04 12:42
just got a friend to test xenia on a different computer same issues 930m i5 5200u 8gb ram

**Comment by PcDivision** [comment] 2016-12-04 12:51
the error was in memory.cc line 856 and is
  if (start_page_number == UINT_MAX || end_page_number == UINT_MAX) {
    // Out of memory.
    XELOGE("BaseHeap::Alloc failed to find contiguous range");
    assert_always("Heap exhausted!");
    return false;
  }

**Comment by PcDivision** [comment] 2016-12-04 12:52
xenia has sufficient memory to run.

**Comment by paulsapps** [comment] 2016-12-04 13:07
pls consider collecting more info instead of spam posting so much!

**Comment by Margen67** [comment] 2019-07-13 21:08
Duplicate of #665

**Closed by Margen67** 2019-07-13 21:08 UTC
Labels: bug
