### ISSUE TITLE
Please add support for Android Devices

### ISSUE THREAD

**Issue by joelos1111** [xenia-project/xenia#2077] opened 2022-10-20 05:40 UTC
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Please consider trying to add some support for Android users/devices in the upcoming days or months, this Emulator looks amazing and if you are able to compile an Android version we all would highly appreciate it. Thanks and have a good day

### Describe what should happen

Please consider trying to add some support for Android users/devices in the upcoming days or months, this Emulator looks amazing and if you are able to compile an Android version we all would highly appreciate it. Thanks and have a good day

**Comment by Wunkolo** [comment] 2022-10-20 06:11
Might wanna check out #2002. This is where the dialog around targeting AArch64 platforms is being sustained.

**Comment by Margen67** [comment] 2022-10-20 07:51
#1878

**Comment by Triang3l** [comment] 2022-10-23 15:18
Closing as largely a duplicate of #1878 and as somewhat invalid and containing no technical info besides a request, and also being a suggestion submitted as a bug.

**Closed by Triang3l** 2022-10-23 15:18 UTC
Labels: bug
