### ISSUE TITLE
Gears Of War 2, 3, judgement graphics device lost new builds xenia on AMD Vega 64

### ISSUE THREAD

**Issue by dante3732** [xenia-project/xenia#2023] opened 2022-05-28 09:42 UTC
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
-  If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
-  (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

There are places in these games where the game crashes constantly, but it also crashes randomly. Driver give TDR error.
It happened beginning with jun 23 2020 build and still not fixed.
There are no crashes  on previous builds.
Windows 11 Pro x64 21H2
AMD Ryzen 5 3600 4.2 Ghz
MSI Radeon VEGA 64 8 Gb HBM2 22.5.1 
2x8 Gb DDR4 3200
![3232](https://user-images.githubusercontent.com/66036249/170819886-e12310f8-f88d-4cc2-96cb-146fb5ce9e41.jpg)

### Describe what should happen

The emulator should not cause the driver to make this error.

### If applicable, upload a logfile and link it here

[xenia.log](https://github.com/xenia-project/xenia/files/8790904/xenia.log)

**Comment by dante3732** [comment] 2022-05-28 09:50
I've only seen this kind of thing in these games. I played a lot in rdr and condemned  2 and there was no such thing.

**Comment by Margen67** [comment] 2022-05-29 07:43
Duplicate of #1774 #1251

**Closed by Margen67** 2022-05-29 07:43 UTC
Labels: duplicate

**Comment by dante3732** [comment] 2022-08-18 12:40
> Duplicate of #1774 #1251
It not rov issue.
