### ISSUE TITLE
"Graphics Device Lost Due to an Internal Error"

### ISSUE THREAD

**Issue by wolfokami321** [xenia-project/xenia#1099] opened 2018-03-05 02:08 UTC
I've been getting this error and haven't been able to use a build since b057ad2
https://gyazo.com/921177afa5a0b0b8d8226bff3dde04f7

Here is the attached log, it's very frustrating because older builds seem to work fine. It can't be my graphics card. I have an Nvidia 965m.
[xenia.log](https://github.com/benvanik/xenia/files/1779268/xenia.log)

**Comment by wolfokami321** [comment] 2018-03-05 02:16
It may be related to XEswap

**Comment by srdjan1995** [comment] 2018-03-08 22:21
I'm having the same issue on my GTX 960. Tried using older drivers, same issue, tried newest Vulkan 1.1 drivers, same issue. Except those new Vulkan drivers seems to be a lot slower for me when using Xenia. Can't test some games due to that "Graphics Device Lost Due to an internal Error" issue. Any help?

**Comment by dany5639** [comment] 2018-04-28 04:34
On Halo 3 ODST, the error pops up at random moments when playing a cinematic or attempting to draw the world, sometimes it works, sometimes not. I was able to force load different maps, managed to set most shaders to use the same shader (prevent decompilation of a large number of shaders). With all the shaders, the crash happens much more frequently. It doesn't always crash at the same point. I'm able to run the cinematic maybe 1/20 attempts.  
The easiest way to replicate it is to simply load a stock Halo 3 ODST game, it should crash with that error after a few seconds of loading the menu.
https://i.imgur.com/Zk7Uzre.png

**Comment by jupiterbjy** [comment] 2018-05-11 12:34
Mine also crash, on GTX960 jetstream oc

Seems like all of us are using 96x numbering devices, could it be the clue?

**Comment by jupiterbjy** [comment] 2018-05-14 18:59
Forgot to add detail to my comment, Issue still intact on build 6807ef36 (May 14 2018).

Now I have a new line with following:

> w> 0000000C libav: Too small input buffer
> w> 0000000C libav:  is not implemented. Update your Libav version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
> w> 0000000C libav: If you want to help, upload a sample of this file to ftp://upload.libav.org/incoming/ and contact the libav-devel mailing list.
> !> 0000000C libav: Could not collect frame!
> A> 0000000C libav failed to decode a frame!

[xenia.log](https://github.com/xenia-project/xenia/files/2002146/xenia.log)

Now I'm not seeing "Graphics Device lost" message anywhere on log file, but just crash - which is now compatibility issue of specific game, at least for me.

**Comment by Blackbird88** [comment] 2018-05-19 18:16
Getting same with GTX 980 in Saints Row 1. The game used to get in-game before.
[Log](https://gist.github.com/Blackbird88/b8f64bda71ec008cf05b2715f65982f4)

**Comment by yotoprules** [comment] 2018-05-24 06:43
Same issue. As soon as i select new game in saints row it gives me this error. GTX 960. i5 8400.

**Comment by awes04** [comment] 2018-05-25 10:26
Same issue here. Right after start running Madden NFL 17 the error message prompts. GTX 750 Ti

**Comment by SirAlden** [comment] 2018-05-28 12:41
Same problem on a GTX 1070 running latest drivers

**Comment by Parovozik** [comment] 2018-05-28 16:27
I think these problems are due to the workaround of the memory leak problem, I'm not sure if this was the best option, maybe fix it.

**Comment by srdjan1995** [comment] 2018-06-01 14:14
Yeah, seems to be fixed. Dante's Inferno works ok for me now, but it's not full speed obviously. Sound and graphics are good. :)

**Comment by NekokoTime** [comment] 2018-06-01 18:28
@wolfokami321 install the new Nvidia beta 397.96 Drive this error has gone out of Xenia
https://developer.nvidia.com/vulkan-driver

**Comment by awes04** [comment] 2018-06-01 22:42
I installed the new Nvidia Beta Drive 397.96 Drive and now I get to the favorite team selection (Madden NFL 17). But while switching through the teams, the the error message prompts again. GTX 750 Ti

**Comment by NekokoTime** [comment] 2018-06-01 22:50
@awes04 UAI strange in GTX 1050 TI 4GB mine does not appear these errors.

**Comment by Outeest** [comment] 2018-06-02 20:29
@NekokoTime How did you get 397.96 version?
I have only 397.93. =\

**Comment by NekokoTime** [comment] 2018-06-02 22:07
@Outeest yes Nvidia Drive Beta 397.96 is available through this link here https://developer.nvidia.com/vulkan-driver
I recommend that I install the Nvidia beta 397.96 Drive to finish with this error above

**Comment by Outeest** [comment] 2018-06-03 09:28
@NekokoTime Btw, the error is disappeared, but Xenia just freezing instead of giving me the error.
I'll install those drivers and also I'll message here if it works or not.

**Comment by Outeest** [comment] 2018-06-03 10:01
Well, I installed the last version of drivers but it doesn't work for me.
I have no errors but the game loading is still freezes on certain time.
For Skate3.
Skate2 has a similar problem: loading is freezing but the animation while loading is going well.
With some weird graphics but it goes.
![weird](https://user-images.githubusercontent.com/39246740/40885404-3f71ab1a-672e-11e8-9dac-f6a8226f0966.PNG)

**Comment by NekokoTime** [comment] 2018-06-03 10:16
@Outeest had instalei Drive Nvidia Beta 397.96 but meu xenia no deu esse congelamento n

**Comment by tjd2** [comment] 2018-06-10 19:09
Never got this error on my ATI Radeon 7700, but my video driver was frequently crashing when playing Banjo Kazooie: Nuts and Bolts (it does not in newer builds)

**Comment by community-college** [comment] 2018-12-19 01:15
Getting this error on a laptop NVIDIA 1050

**Comment by SHN3RT** [comment] 2019-01-20 17:44
Hi,
I have the same problem, when I open Banjo-Kazooie: Nuts & Bolts on GTX 1080TI. 
[xenia.log](https://github.com/xenia-project/xenia/files/2776891/xenia.log)
Anyone know, what is solution for this issue?

**Comment by chris-hawley** [comment] 2019-01-21 02:20
@SHN3RT you are using vulkan. The vulkan backend is not nearly as far along as the Directx 12 backend. You can find the latest Directx 12 build here. 
https://ci.appveyor.com/api/projects/benvanik/xenia/artifacts/xenia-d3d12.zip?branch=d3d12&job=Configuration%3A%20Release&pr=false

**Comment by Dragoon2k19** [comment] 2019-01-28 09:14
i just got this error Using DX12 version.....

**Comment by eyewee** [comment] 2019-03-09 20:40
I'm constantly getting this same error as above "Graphics Device Lost Due to an Internal Error" with Midnight Club LA on i5 2500k, gtx 1070, wether it be with MNC4 or RDR (I've tested only these 2), however it gives white screen with hud and all interaction present when in vulkan version. 
Fresh windows 10 installed with fresh drivers (419.65), I've tested about 15 older dx12 builds, the same pb. Tested 397.96 and the beta 419.34 drivers as well.

**Comment by eyewee** [comment] 2019-03-12 23:50
Update: the issue is resolved, I've reinstalled windows 10, installed latest drivers and got fresh update from the update center. Everything works.

**Comment by Margen67** [comment] 2019-03-12 23:51
If the issue is resolved then close it.

**Comment by eyewee** [comment] 2019-03-12 23:53
I didn't open the topic to be able to close it :|

**Comment by lif3mau5** [comment] 2019-04-18 20:40
Hi, get the same error in Red Dead Redemption, only when I overclock 
my GPU (after I flashed the latest Bios for my GPU).
Without overclocking I get only after 2 hours of gaming a crash ... interessting!
Flashed back my Bios and nothing happens, no error? 
Have a MSI GTX 1080 Ti (Micron DDR5X) with latest Bios.
Special thanks to the awesome work from dev's here! (=

**Comment by Margen67** [comment] 2019-10-28 06:29
This kind of generic error belongs in a game-compatibility report.

**Closed by Margen67** 2019-10-28 06:29 UTC
Labels: bug, gpu, gpu-d3d12, gpu-vulkan

**Comment by joilsonnunes78** [comment] 2023-01-19 19:25
alguem conseguiu corrigir?
