### ISSUE TITLE
xenia.exe - Entry Point Not Found

### ISSUE THREAD

**Issue by Ironstone1** [xenia-project/xenia#1206] opened 2018-07-08 21:06 UTC
I'm getting the following error when I try to run the program, im using Windows 7 64-bit:

The procedure entry point RtlAddGrowableFunctionTable could not be located in the dynamic link library ntdll.dll.

i downloaded the exe from http://xenia.jp/download/

**Comment by Parovozik** [comment] 2018-07-08 21:32
Because minimum system requirement is Windows 8.1 x64

**Comment by Ironstone1** [comment] 2018-07-08 21:38
Is there anyway to get it working on Windows 7? could I not just download the required DLL libraries used on latter operating systems?

**Comment by Ironstone1** [comment] 2018-07-08 22:36
Do you have plans on creating a windows 7 compatible version of the program?

**Comment by maxton** [comment] 2018-07-08 23:05
From the FAQ
> Support for older operating systems and processors will not be added unless a contributor steps up to build and maintain them.

**Comment by Margen67** [comment] 2018-07-09 04:31
Duplicate of #295

**Closed** 2018-07-27 19:05 UTC
