### ISSUE TITLE
bakugan battle brawlers flickering items and cards 

### ISSUE THREAD

**Issue by aleksikan** [xenia-project/xenia#1907] opened 2021-10-30 05:58 UTC
![image](https://user-images.githubusercontent.com/93398767/139522256-3015717b-43dc-424b-97f7-ad076105b868.png)
![image](https://user-images.githubusercontent.com/93398767/139522265-39d1f23c-fbb1-4dd3-8beb-ee80461ff34f.png)
![image](https://user-images.githubusercontent.com/93398767/139522452-a7d0a534-3d6f-46d6-9a93-2dcf3aa2a9c4.png)

**Comment by aleksikan** [comment] 2021-10-30 06:09
rov and f5 doesn't help

**Comment by Margen67** [comment] 2021-10-30 06:24
Duplicate of #1906

**Comment by aleksikan** [comment] 2021-10-30 06:39
![image](https://user-images.githubusercontent.com/93398767/139523250-d0e0c133-84eb-4de1-9799-2584e252791c.png)

**Comment by illusion0001** [comment] 2021-10-30 09:30
Duplicate of #1906

**Closed by illusion0001** 2021-10-30 09:30 UTC

**Comment by aleksikan** [comment] 2021-10-30 13:52
> Duplicate of #1906

damn bruh i already apologized ion know how this app works but can someone please help me or look into this and not just comment about me posting this twice on accident? 
dis the only game me n my friends wanna play on xenia and ofcourse with our luck it is the broken one

**Comment by Masamune3210** [comment] 2021-10-30 16:29
no, one because it makes more sense to have all information under one issue instead of multiple, but mostly because that's not how any of this works. Games are going to have issues, welcome to the world of emulation
