### ISSUE TITLE
[DX12] System hangs on older GPUs

### ISSUE THREAD

**Issue by FateForWindows** [xenia-project/xenia#1221] opened 2018-10-03 21:50 UTC
[//]: # (Describe what's going wrong:)
With the DX12 build, upon starting a game (in my case, Sonic '06 or Sonic Unleashed), the PC slows down to a crawl. This only seems to happen when the game is loading, and the point at which it gets to is not always consistent. E.g. in some cases, it reaches the title screen of '06, other times it doesn't even make it past the first loading screen. The game slows down to a crawl after the first loading screen. In Sonic Unleashed, it is consistently able to reach the loading screen after the Hedgehog Engine logo; after that, the PC hangs. Before the PC hangs, it slows down to a crawl for a few moments and the entire PC hangs shortly after. I am using build b77ffe3.

[//]: # (Describe what should happen:)
Game runs or Xenia crashes/Xenia hangs; Entire PC should not hang.

[//]: # (If applicable, provide a callstack here - esp. for crashes)

[//]: # (If applicable, upload a logfile and link it here)
[xenia.log](https://github.com/xenia-project/xenia/files/2444044/xenia.log)

UPDATE: Thanks to recent commits Xenia has started working on many GPUs affected. Still waiting for more feedback before I close this issue.

**Comment by MarcoEstevez** [comment] 2018-10-04 05:02
It happens the same here - ridge racer - when entering a race, having to entirerly boot my laptop

**Comment by LuismaSP89** [comment] 2018-10-04 13:40
@FateForWindows It sounds like a memory leak... did you try with other games or older builds of xenia (The latest build using vulkan) ?

**Comment by MarcoEstevez** [comment] 2018-10-04 14:32
Latest vulkan doesn't has this behaviour, I also tested Daytona USA with same problem, it hangs to the point the only way to recover is hard reset the computer, that's why I did not test more titles

Ridge Racer, works fine during menus, but daytona freezes as soon as it boots.

**Comment by 4XPG** [comment] 2018-10-04 15:04
I'm having same issue with some games I tested on DX12 build (Armored Core 4, Armored Core For Answer, Ace Combat 6) using GTX960M

Perhaps mobile graphic cards aren't compatible with DX12 build?

**Comment by Parovozik** [comment] 2018-10-04 17:17
XENIA-DX12 required powerfull GPU with 4GB VRAM just for start (or your PC will hangs on start any game)

**Comment by Parovozik** [comment] 2018-10-04 20:28
I know what PC will hangs on Xenia-DX12 for GT640 2GB, GTX750ti 2GB and GTX760 2GB, but on Xenia-Vulkan they works is perfectly. Most likely your PC will hangs on any GPU with less than 4GB VRAM

**Comment by LuismaSP89** [comment] 2018-10-04 22:35
@Parovozik 
Hi Parovozik, and sorry for the offtopic, but... could you tell me how is the command to change language in xenia? I wanted for months to set spanish language in my games and I searched everywhere for the Xenia´s command line with no results, and I know you were developing a PR to do this.
Thanks in advance, and sorry again for the offtopic.

**Comment by 4XPG** [comment] 2018-10-05 00:42
my GTX 960M has 4GB VRAM but it still hangs anyway
![image](https://user-images.githubusercontent.com/4043537/46510139-43411b00-c871-11e8-9ee6-f04514f5444b.png)

**Comment by Parovozik** [comment] 2018-10-05 02:13
@4XPG 960m = desktop gtx750ti GPU and they too weak for Xenia-DX12 anyway.
As option there show summary shared memory (real 2GB)

**Comment by LuismaSP89** [comment] 2018-10-05 02:30
@parovozik Uh, I see... what a shame... btw thanks a lot for your reply ^^

**Comment by 4XPG** [comment] 2018-10-05 06:35
@Parovozik ah yes, I get it. Thanks for the explanation.

**Comment by LuismaSP89** [comment] 2018-10-06 02:59
@Parovozik Thanks a lot man, let´s hope that the PR with the languages can be merged soon in order to let the users have a language selector :P

**Comment by Triang3l** [comment] 2018-10-08 13:50
Caused by the usage of placed resources for render targets to reduce VRAM usage — something in broken in their implementation on older (resource heap tier 1) Nvidia GPUs, currently doing random things hoping something will make it stop hanging. Later I will switch to committed resources though to perform EDRAM load/store — which is currently the GPU bottleneck — less frequently, but the unavailability of render target height makes it a bit difficult (render targets would need 2560 height without AA and 5120 with AA possibly).

**Comment by juaniglesiasag** [comment] 2018-10-27 11:34
Same problem here with GTX Titan 6 GB (Kepler)

**Comment by xbox360pad** [comment] 2018-12-02 03:04
> We need more statistics, but for now I don’t know anyone who has it working on 2GB VRAM (very interesting about gtx1050 2GB and 1060 3GB)

XENIA-DX12 was working fine on my old HD7950 3GB.

**Comment by FateForWindows** [comment] 2018-12-02 15:36
DX12 branch is working on my 860M now.

**Comment by Subarasheese** [comment] 2018-12-02 16:32
I can confirm DX12 now works on my GTX 760 (2gb).

**Comment by juaniglesiasag** [comment] 2018-12-02 16:35
> Same problem here with GTX Titan 6 GB (Kepler)
> 
> https://i.imgur.com/igvr6O3.png

I have updated Xenia DX12 and it does not work :(

**Comment by win98and95** [comment] 2018-12-02 16:43
@juaniglesiasag provide logs.
also try updating your driver to the latest version.

**Comment by FateForWindows** [comment] 2018-12-02 18:01
> > Same problem here with GTX Titan 6 GB (Kepler)
> > https://i.imgur.com/igvr6O3.png
> 
> I have updated Xenia DX12 and it does not work :(

Just to be sure it's hanging or was hanging your whole computer, right?

**Comment by LuismaSP89** [comment] 2018-12-02 20:46
@juaniglesiasag I think your problem is related with this: https://github.com/xenia-project/xenia/issues/1251

You´re not the only one, but Triangle is working on a solution.

**Comment by FateForWindows** [comment] 2018-12-02 23:02
> > @juaniglesiasag provide logs.
> > also try updating your driver to the latest version.
> 
> > Just to be sure it's hanging or was hanging your whole computer, right?
> 
> I have the latest version of the Nvidia drivers. Only Xenia freezes.
> 
> Screenshot of the fault and the log:
> 
> ![desktop screenshot 2018 12 02 - 21 22 11 04](https://user-images.githubusercontent.com/43917465/49344543-19418480-f679-11e8-986f-75429a27e3bf.png)
> 
> [xenia.log](https://github.com/xenia-project/xenia/files/2637354/xenia.log)
> 
> Thanks for your help

Yeah, that's a different error than what the topic is about (the whole operating system hanging). Like Luisma said it's probably related to #1251 .

**Comment by juaniglesiasag** [comment] 2018-12-03 00:44
Before the update, Xenia crashes my computer completely. This problem has been resolved, now the problem is another... Thanks to all!

**Closed** 2019-02-21 09:53 UTC
Labels: d3d12, gpu
