### ISSUE TITLE
Linux compile crash with errors

### ISSUE THREAD

**Issue by Mte90** [xenia-project/xenia#1735] opened 2021-01-10 23:01 UTC
[//]: # (Describe what's going wrong:)

```
./xb build --config=release 
Building release...

- running premake...
Building configurations...
    Baking aes_128...
    Baking capstone...
    Baking dxbc...
    Baking discord-rpc...
    Baking cxxopts...
    Baking cpptoml...
    Baking fmt...
    Baking glslang-spirv...
    Baking imgui...
    Baking libavcodec...
    Baking libavutil...
    Baking mspack...
    Baking snappy...
    Baking spirv-tools...
    Baking volk...
    Baking xxhash...
    Baking xenia-core...
    Baking xenia-app-discord...
    Baking xenia-apu...
    Baking xenia-apu-nop...
    Baking xenia-base...
    Baking xenia-base-tests...
    Baking xenia-cpu...
    Baking xenia-cpu-tests...
    Baking xenia-cpu-ppc-tests...
    Baking xenia-cpu-backend-x64...
    Baking xenia-debug-ui...
    Baking xenia-gpu...
    Baking xenia-gpu-shader-compiler...
    Baking xenia-gpu-null...
    Baking xenia-gpu-vulkan...
    Baking xenia-gpu-vulkan-trace-viewer...
    Baking xenia-gpu-vulkan-trace-dump...
    Baking xenia-hid...
    Baking xenia-hid-demo...
    Baking xenia-hid-nop...
    Baking xenia-kernel...
    Baking xenia-ui...
    Baking xenia-ui-spirv...
    Baking xenia-ui-vulkan...
    Baking xenia-ui-window-vulkan-demo...
    Baking xenia-vfs...
    Baking xenia-vfs-dump...
    Baking xenia-apu-sdl...
    Baking xenia-helper-sdl...
    Baking xenia-hid-sdl...
    Baking xenia-app...
Running action 'gmake2'...
Done (2088ms).

- building (all):release...
make: ingresso nella directory «/home/mte90/Desktop/xenia/build»
==== Building aes_128 (release_linux) ====
==== Building capstone (release_linux) ====
==== Building dxbc (release_linux) ====
==== Building discord-rpc (release_linux) ====
Linking dxbc
Linking aes_128
Linking capstone
Linking discord-rpc
==== Building cpptoml (release_linux) ====
==== Building cxxopts (release_linux) ====
==== Building fmt (release_linux) ====
==== Building glslang-spirv (release_linux) ====
==== Building imgui (release_linux) ====
Creating obj/Linux/Release/Linux/Release/fmt
Creating obj/Linux/Release/Linux/Release/glslang-spirv
format.cc
Creating obj/Linux/Release/Linux/Release/imgui
InReadableOrder.cpp
imgui.cpp
os.cc
==== Building libavutil (release_linux) ====
Creating obj/Linux/Release/Linux/Release/libavutil
adler32.c
aes.c
Logger.cpp
atomic.c
audio_fifo.c
avstring.c
../third_party/libav/libavutil/avstring.c:57:16: warning: returning 'const char *' from a function with result type 'char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        return s1;
               ^~
../third_party/libav/libavutil/avstring.c:61:20: warning: returning 'const char *' from a function with result type 'char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
            return s1;
                   ^~
../third_party/libav/libavutil/avstring.c:71:16: warning: returning 'const char *' from a function with result type 'char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        return haystack;
               ^~~~~~~~
../third_party/libav/libavutil/avstring.c:75:20: warning: returning 'const char *' from a function with result type 'char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
            return haystack;
                   ^~~~~~~~
4 warnings generated.
base64.c
blowfish.c
buffer.c
channel_layout.c
cpu.c
In file included from ../third_party/libav/libavutil/cpu.c:39:
/usr/include/x86_64-linux-gnu/sys/sysctl.h:21:2: error: "The <sys/sysctl.h> header is deprecated and will be removed." [-Werror,-W#warnings]
#warning "The <sys/sysctl.h> header is deprecated and will be removed."
 ^
../third_party/libav/libavutil/cpu.c:97:76: error: implicit conversion from 'long' to 'double' changes value from 9223372036854775807 to 9223372036854775808 [-Werror,-Wimplicit-const-int-float-conversion]
        { "flags"   , NULL, 0, AV_OPT_TYPE_FLAGS, { .i64 = 0 }, INT64_MIN, INT64_MAX, .unit = "flags" },
        ~                                                                  ^~~~~~~~~
/usr/include/stdint.h:124:22: note: expanded from macro 'INT64_MAX'
# define INT64_MAX              (__INT64_C(9223372036854775807))
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/stdint.h:106:24: note: expanded from macro '__INT64_C'
#  define __INT64_C(c)  c ## L
                        ^~~~~~
<scratch space>:308:1: note: expanded from here
9223372036854775807L
^~~~~~~~~~~~~~~~~~~~
2 errors generated.
make[1]: *** [libavutil.make:291: obj/Linux/Release/Linux/Release/libavutil/cpu.o] Errore 1
make: *** [Makefile:239: libavutil] Errore 2
make: *** Attesa per i processi non terminati....
SPVRemapper.cpp
SpvBuilder.cpp
In file included from ../third_party/glslang-spirv/SPVRemapper.cpp:45:
In file included from ../third_party/glslang-spirv/Include/Common.h:103:
../third_party/glslang-spirv/Include/PoolAlloc.h:307:54: error: 'operator=' is a private member of 'glslang::TPoolAllocator'
    void setAllocator(TPoolAllocator* a) { allocator = *a; }
                                           ~~~~~~~~~ ^ ~~
../third_party/glslang-spirv/Include/PoolAlloc.h:244:21: note: declared private here
    TPoolAllocator& operator=(const TPoolAllocator&);  // don't allow assignment operator
                    ^
1 error generated.
make[1]: *** [glslang-spirv.make:184: obj/Linux/Release/Linux/Release/glslang-spirv/SPVRemapper.o] Errore 1
make[1]: *** Attesa per i processi non terminati....
imgui_demo.cpp
imgui_draw.cpp
imgui_widgets.cpp
make: *** [Makefile:221: glslang-spirv] Errore 2
Linking imgui
Linking fmt
make: uscita dalla directory «/home/mte90/Desktop/xenia/build»

ERROR: build failed with one or more errors.
```

Also a note in building.md is not mentioned for Linux but require LLVM to be installed or the compilation doesn't work.

**Comment by JoelLinn** [comment] 2021-01-10 23:29
Your clang version likely is "to new". Try clang-9. A working build environment under ubuntu:bionic is described [in this dockerfile](https://github.com/JoelLinn/docker-xenia-buildenv/blob/master/Dockerfile.1) - just take it as a guide. On newer distros you will encounter a missing sysctl.h header as well, the config_lin.h for libav needs to have sysctl deactivated to build on those.

Unfortunately newer clang versions don't work at the moment because of incompatible third party libraries, which can't be easily upgraded or another feature which would upgrade those is being worked on. Make sure to take a look at the main Linux Issue #1430 to get an overview.

**Comment by Mte90** [comment] 2021-01-10 23:32
I have clang-9 on my machine, but I don't know how to specify it.

I can do some other tests. I saw that ticket I just want to see if I can run a game for game hacking purpose that I will do later on a real xbox, so I don't care right now of a lot of things.

**Comment by JoelLinn** [comment] 2021-01-10 23:37
through environment variables, the usual `CC=clang-9` `CXX=clang++-9` and `AR=llvm-ar-9`

Spoiler: It can't run a game right now, there is a lot of issues and missing features.

btw, I saw you made some PRs to the free60 project. Don't know what you are trying to do exactly but there are people on the discord who maybe can point you some directions ("newer" free60 work is kinda spread around the web :/ )

**Comment by Mte90** [comment] 2021-01-16 15:50
I am trying to mod a xbox360 game for fun, so I am just looking a way to investigate on how works.
I contributed on free60 because their wiki had some issue and I wanted to help.

About xenia I tried with `./xb build --config=release --target linux CC=clang-9` but doesn't work.

If the linux version is not working will try with wine or a virtual machine.

**Comment by kiyotaka4946g** [comment] 2021-02-22 09:21
<sys/sysctl.h> is removed from Linux kernel.
This unmerged PR fixed the problem for me.
https://github.com/xenia-project/libav/pull/4/commits/f68fa2ff5a5d4355f128d8b4b9689011b01e3014

**Comment by Shoegzer** [comment] 2021-04-29 16:09
Confirmed here too with Linux Mint 20.1, with gcc 10.2.0.  Deprecated `sys/stsctl.h`.  

@JoelLinn what are the blockers to merging your PR?  Would be nice to have this project compiling in Linux so more people can start testing with it.

**Comment by JoelLinn** [comment] 2021-04-29 16:31
gcc is largely untested and will likely complain about warnings or unknown flags

There currently is work underway to replace libav #1777 
It then builds fine on ubuntu 20.10 and current clang

**Comment by Shoegzer** [comment] 2021-04-29 16:47
Thanks @JoelLinn I missed your PR but that's indeed good news.  You're right of course about Xenia being tricky with unique aspects.  Others that come to mind are support for a decent graphics backed i.e. Vulkan and cross-platform input subsystem, without either of which thorough testing would not be possible.  But hey, compiling is a great first step and I certainly appreciate your efforts.

**Comment by Shoegzer** [comment] 2021-05-01 18:49
With the PR merged today building progresses further but eventually fails again:
```
error: unknown warning option '-Werror=implicit-const-int-float-conversion'; did you mean '-Werror=implicit-int-float-conversion'? [-Werror,-Wunknown-warning-option]
make[1]: *** [libavutil.make:338: obj/Linux/Debug/Linux/Debug/libavutil/adler32.o] Error 1
X86Disassembler.c
make: *** [Makefile:221: libavutil] Error 2
```
Full build log is [here](https://pastebin.com/785Md0vq)

Again this is with Linux Mint 20.1 and gcc 10.2.0, testing commit b5fc1efad52f934cb8f4a85108f98ec0b6eec50e.

**Comment by JoelLinn** [comment] 2021-05-01 19:39
Please try with clang 10 or 11

**Comment by Shoegzer** [comment] 2021-05-01 23:34
Thanks, but that's what I had installed:
```
$ clang --version
clang version 10.0.0-4ubuntu1 
```
Also, I'm just doing "xb setup" followed by "xb build".  Is anything else needed?  While the steps are pretty clearly defined in the WIndows section of the [build instructions](https://github.com/xenia-project/xenia/blob/master/docs/building.md), they aren't so much for Linux.

**Comment by JoelLinn** [comment] 2021-05-02 19:19
Yes, clang10 seems to be missing that specific warning (and flag).
We briefly discussed and agreed upon disabling warnings=fatal for all third party projects to fix issues like this in a sustainable manner. No PR yet.

**Comment by Shoegzer** [comment] 2021-05-04 04:44
Thank you for #1792 @JoelLinn.  I can compile successfully although the resulting binary coredumps when run, as shown [here](https://pastebin.com/MW8NEeL8).  I believe this is in line with your comment earlier:

> Mind that just being able to build the project doesn't mean it works.

In any event I think this issue can be closed @Mte90.  I can create a separate issue for the runtime problem if necessary.

**Comment by JoelLinn** [comment] 2021-05-04 07:07
Warnings in third party projects aren‘t treated as error any more. Hence, this particular issue is fixed.
FYI, Linux support is tracked in #1430

**Closed by JoelLinn** 2021-05-04 07:07 UTC

**Comment by MoonDragon-MD** [comment] 2022-01-08 15:23
Hi, sorry if I get in the way, I would like to try Xenia on Ubuntu 20.04. I started installing the following dependencies:
`sudo apt-get install libgtk-3-dev libpthread-stubs0-dev liblz4-dev libx11-dev libx11-xcb-dev libvulkan-dev libsdl2-dev libiberty-dev libunwind-dev libc++-dev libc++abi-dev`
`sudo -E apt-get -yq --no-install-suggests --no-install-recommends install clang-6.0 clang-format-6.0`
`sudo apt-get install python3-opencv`
"cd folder"
`./xb build --config=release --target linux CC=clang-6`
but I get the following error:
`./xb: line 1: xenia-build: command not found`
So I tried with:
`python xenia-build premake --devenv=cmake`
but I get the following error:
`ERROR: Python 3.4+ must be installed and on PATH`
Is anyone kind enough to explain to me step by step how to do it? Thanks in advance
