### ISSUE TITLE
Xenia's audio (sound effect) lag / out of sync / delay issue

### ISSUE THREAD

**Issue by mrmatteastwood** [xenia-project/xenia#1806] opened 2021-05-11 08:57 UTC
**Steps to Reproduce**
1. Launch a game in Xenia, e.g. GoldenEye XBLA (Bean)
2. Enter a part of the game where it responds to user input with sound effects (e.g. menu item selection, gunfire)

**Current Results**
Audio noticeably lags behind user input. It feels like about half a second.

**Expected Results**
Audio should play immediately when user performs an action in-game.

**Notes:**
- Issue encountered on GoldenEye XBLA (Bean)
- Issue can be heard e.g. in this video, starting at 5:50: https://youtu.be/ZyQB1JP1E8M?t=350 The sound plays noticeably after the player selects a menu item.
- Issue occurs on Xenia master from Apr 27, 2021 and Canary from May 11, 2021
- Issue occurs regardless of apu setting in xenia.config.toml (any, nop, sdl, xaudio2)
- Issue occurs regardless of ffmpeg_verbose setting in xenia.config.toml (any, nop, sdl, xaudio2)
- Apparently, this issue is not game-specific. A Google search for "xenia audio lag" reveals numerous instances of users having the same problem in other games.
- Log from running Bean on May 11, 2021 attached
- Issue encountered on PC with Intel Core i7-4970k CPU, GTX 1080 Ti, 32 GB RAM, Windows 10 Pro

_Hope this is the right way to report this bug. It seems that there's no other bug report about this except the one from 2018 (https://github.com/xenia-project/xenia/issues/1156), at which point audio lag seemed to be completely different (it feels like less than half a second now, whereas users reported several seconds back then).

Hence, I'm opening this new bug report to see if anybody knows a workaround and to allow tracking of progress on this issue. If there's any other way I can contribute to this, please let me know. I'll be happy to test other Xbox 360 games, my brother still has a number of them and I'll borrow them next time I see him._

[xenia.log](https://github.com/xenia-project/xenia/files/6457810/xenia.log)

**Comment by Margen67** [comment] 2021-05-12 04:57
Duplicate of #1156

**Comment by illusion0001** [comment] 2021-05-12 06:08
Duplicate of #1156

**Closed by illusion0001** 2021-05-12 06:08 UTC
